spring.application.name=FoodCommand

spring.datasource.url=jdbc:postgresql://localhost/FoodCommand
spring.datasource.username=postgres
spring.datasource.password=Sen@c2023
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.expiracao=5
spring.secret= kkkkkk12345678910111213141516
spring.emissor= alunoericson